[2025-07-17T17:15:06.365+0000] {processor.py:161} INFO - Started process (PID=1956) to work on /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:15:06.371+0000] {processor.py:830} INFO - Processing file /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-17T17:15:06.379+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:15:06.376+0000] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:15:06.489+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:15:06.464+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-17T17:15:06.496+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:15:06.493+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-17T17:15:06.500+0000] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:15:06.560+0000] {processor.py:183} INFO - Processing /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.229 seconds
[2025-07-17T17:19:21.783+0000] {processor.py:161} INFO - Started process (PID=2040) to work on /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:19:21.825+0000] {processor.py:830} INFO - Processing file /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-17T17:19:21.864+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:19:21.844+0000] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:19:22.054+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:19:22.045+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-17T17:19:22.058+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:19:22.057+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-17T17:19:22.059+0000] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:19:22.222+0000] {processor.py:183} INFO - Processing /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.667 seconds
[2025-07-17T17:21:43.033+0000] {processor.py:161} INFO - Started process (PID=2111) to work on /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:21:43.038+0000] {processor.py:830} INFO - Processing file /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-17T17:21:43.044+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:21:43.042+0000] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:21:43.112+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:21:43.098+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-17T17:21:43.117+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:21:43.114+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-17T17:21:43.119+0000] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:21:43.168+0000] {processor.py:183} INFO - Processing /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.212 seconds
[2025-07-17T17:25:22.038+0000] {processor.py:161} INFO - Started process (PID=2255) to work on /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:25:22.042+0000] {processor.py:830} INFO - Processing file /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-17T17:25:22.052+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:25:22.049+0000] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:25:22.195+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:25:22.159+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-17T17:25:22.203+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:25:22.199+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-17T17:25:22.206+0000] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:25:22.292+0000] {processor.py:183} INFO - Processing /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.283 seconds
[2025-07-17T17:33:20.479+0000] {processor.py:161} INFO - Started process (PID=2495) to work on /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:33:20.483+0000] {processor.py:830} INFO - Processing file /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-17T17:33:20.487+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:33:20.485+0000] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:33:20.542+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:33:20.529+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-17T17:33:20.550+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:33:20.547+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-17T17:33:20.552+0000] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:33:20.615+0000] {processor.py:183} INFO - Processing /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.162 seconds
[2025-07-17T17:35:38.040+0000] {processor.py:161} INFO - Started process (PID=2570) to work on /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:35:38.058+0000] {processor.py:830} INFO - Processing file /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-17T17:35:38.105+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:35:38.081+0000] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:35:38.551+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:35:38.536+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-17T17:35:38.553+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:35:38.552+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-17T17:35:38.554+0000] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:35:38.667+0000] {processor.py:183} INFO - Processing /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.739 seconds
[2025-07-17T17:39:19.589+0000] {processor.py:161} INFO - Started process (PID=2704) to work on /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:39:19.593+0000] {processor.py:830} INFO - Processing file /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-17T17:39:19.603+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:39:19.598+0000] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:39:19.708+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:39:19.689+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-17T17:39:19.715+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:39:19.712+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-17T17:39:19.718+0000] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:39:19.774+0000] {processor.py:183} INFO - Processing /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.215 seconds
[2025-07-17T17:42:39.322+0000] {processor.py:161} INFO - Started process (PID=2820) to work on /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:42:39.324+0000] {processor.py:830} INFO - Processing file /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-17T17:42:39.327+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:42:39.325+0000] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:42:39.450+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:42:39.424+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-17T17:42:39.452+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:42:39.451+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-17T17:42:39.453+0000] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:42:39.479+0000] {processor.py:183} INFO - Processing /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.169 seconds
[2025-07-17T17:46:31.495+0000] {processor.py:161} INFO - Started process (PID=2937) to work on /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:46:31.499+0000] {processor.py:830} INFO - Processing file /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-17T17:46:31.503+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:46:31.501+0000] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:46:31.561+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:46:31.549+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-17T17:46:31.565+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:46:31.563+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-17T17:46:31.566+0000] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:46:31.604+0000] {processor.py:183} INFO - Processing /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.136 seconds
[2025-07-17T17:48:46.887+0000] {processor.py:161} INFO - Started process (PID=3045) to work on /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:48:46.890+0000] {processor.py:830} INFO - Processing file /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-17T17:48:46.893+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:48:46.892+0000] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:48:46.943+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:48:46.931+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-17T17:48:46.947+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:48:46.945+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-17T17:48:46.949+0000] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:48:46.979+0000] {processor.py:183} INFO - Processing /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.110 seconds
[2025-07-17T17:50:44.658+0000] {processor.py:161} INFO - Started process (PID=3147) to work on /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:50:44.661+0000] {processor.py:830} INFO - Processing file /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-17T17:50:44.666+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:50:44.664+0000] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:50:44.715+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:50:44.703+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-17T17:50:44.718+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:50:44.717+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-17T17:50:44.720+0000] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:50:44.752+0000] {processor.py:183} INFO - Processing /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.113 seconds
[2025-07-17T17:52:56.544+0000] {processor.py:161} INFO - Started process (PID=3252) to work on /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:52:56.548+0000] {processor.py:830} INFO - Processing file /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-17T17:52:56.551+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:52:56.550+0000] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:52:56.590+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:52:56.581+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-17T17:52:56.592+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:52:56.591+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-17T17:52:56.594+0000] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:52:56.620+0000] {processor.py:183} INFO - Processing /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.094 seconds
[2025-07-17T17:55:00.399+0000] {processor.py:161} INFO - Started process (PID=3353) to work on /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:55:00.403+0000] {processor.py:830} INFO - Processing file /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-17T17:55:00.407+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:55:00.406+0000] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:55:00.448+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:55:00.440+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-17T17:55:00.451+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:55:00.450+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-17T17:55:00.453+0000] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:55:00.484+0000] {processor.py:183} INFO - Processing /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.103 seconds
[2025-07-17T17:57:04.143+0000] {processor.py:161} INFO - Started process (PID=3454) to work on /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:57:04.147+0000] {processor.py:830} INFO - Processing file /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-17T17:57:04.150+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:57:04.148+0000] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:57:04.194+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:57:04.185+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-17T17:57:04.197+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:57:04.196+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-17T17:57:04.198+0000] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:57:04.230+0000] {processor.py:183} INFO - Processing /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.108 seconds
[2025-07-17T17:59:08.715+0000] {processor.py:161} INFO - Started process (PID=3554) to work on /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:59:08.719+0000] {processor.py:830} INFO - Processing file /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-17T17:59:08.722+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:59:08.721+0000] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:59:08.758+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:59:08.750+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-17T17:59:08.761+0000] {logging_mixin.py:188} INFO - [2025-07-17T17:59:08.760+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-17T17:59:08.762+0000] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T17:59:08.792+0000] {processor.py:183} INFO - Processing /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.096 seconds
[2025-07-17T18:01:18.491+0000] {processor.py:161} INFO - Started process (PID=3659) to work on /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T18:01:18.495+0000] {processor.py:830} INFO - Processing file /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-17T18:01:18.498+0000] {logging_mixin.py:188} INFO - [2025-07-17T18:01:18.496+0000] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T18:01:18.540+0000] {logging_mixin.py:188} INFO - [2025-07-17T18:01:18.532+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-17T18:01:18.543+0000] {logging_mixin.py:188} INFO - [2025-07-17T18:01:18.542+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-17T18:01:18.546+0000] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T18:01:18.581+0000] {processor.py:183} INFO - Processing /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.114 seconds
[2025-07-17T18:03:19.466+0000] {processor.py:161} INFO - Started process (PID=3764) to work on /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T18:03:19.470+0000] {processor.py:830} INFO - Processing file /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-17T18:03:19.475+0000] {logging_mixin.py:188} INFO - [2025-07-17T18:03:19.473+0000] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T18:03:19.538+0000] {logging_mixin.py:188} INFO - [2025-07-17T18:03:19.525+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-17T18:03:19.542+0000] {logging_mixin.py:188} INFO - [2025-07-17T18:03:19.541+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-17T18:03:19.544+0000] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T18:03:19.580+0000] {processor.py:183} INFO - Processing /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.140 seconds
[2025-07-17T18:05:21.012+0000] {processor.py:161} INFO - Started process (PID=3865) to work on /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T18:05:21.015+0000] {processor.py:830} INFO - Processing file /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-17T18:05:21.019+0000] {logging_mixin.py:188} INFO - [2025-07-17T18:05:21.017+0000] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T18:05:21.068+0000] {logging_mixin.py:188} INFO - [2025-07-17T18:05:21.057+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-17T18:05:21.072+0000] {logging_mixin.py:188} INFO - [2025-07-17T18:05:21.070+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-17T18:05:21.073+0000] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T18:05:21.110+0000] {processor.py:183} INFO - Processing /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.127 seconds
[2025-07-17T18:07:26.283+0000] {processor.py:161} INFO - Started process (PID=3966) to work on /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T18:07:26.286+0000] {processor.py:830} INFO - Processing file /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-17T18:07:26.290+0000] {logging_mixin.py:188} INFO - [2025-07-17T18:07:26.288+0000] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T18:07:26.331+0000] {logging_mixin.py:188} INFO - [2025-07-17T18:07:26.323+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-17T18:07:26.333+0000] {logging_mixin.py:188} INFO - [2025-07-17T18:07:26.332+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-17T18:07:26.335+0000] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T18:07:26.361+0000] {processor.py:183} INFO - Processing /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2025-07-17T18:09:38.303+0000] {processor.py:161} INFO - Started process (PID=4071) to work on /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T18:09:38.307+0000] {processor.py:830} INFO - Processing file /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-17T18:09:38.312+0000] {logging_mixin.py:188} INFO - [2025-07-17T18:09:38.310+0000] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T18:09:38.369+0000] {logging_mixin.py:188} INFO - [2025-07-17T18:09:38.356+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-17T18:09:38.372+0000] {logging_mixin.py:188} INFO - [2025-07-17T18:09:38.370+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-17T18:09:38.375+0000] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T18:09:38.412+0000] {processor.py:183} INFO - Processing /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.144 seconds
[2025-07-17T18:11:45.223+0000] {processor.py:161} INFO - Started process (PID=4173) to work on /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T18:11:45.226+0000] {processor.py:830} INFO - Processing file /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-17T18:11:45.231+0000] {logging_mixin.py:188} INFO - [2025-07-17T18:11:45.229+0000] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T18:11:45.277+0000] {logging_mixin.py:188} INFO - [2025-07-17T18:11:45.269+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-17T18:11:45.280+0000] {logging_mixin.py:188} INFO - [2025-07-17T18:11:45.278+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-17T18:11:45.281+0000] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T18:11:45.315+0000] {processor.py:183} INFO - Processing /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.111 seconds
[2025-07-17T18:13:55.385+0000] {processor.py:161} INFO - Started process (PID=4276) to work on /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T18:13:55.387+0000] {processor.py:830} INFO - Processing file /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-17T18:13:55.392+0000] {logging_mixin.py:188} INFO - [2025-07-17T18:13:55.390+0000] {dagbag.py:545} INFO - Filling up the DagBag from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T18:13:55.499+0000] {logging_mixin.py:188} INFO - [2025-07-17T18:13:55.463+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-17T18:13:55.504+0000] {logging_mixin.py:188} INFO - [2025-07-17T18:13:55.502+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-17T18:13:55.507+0000] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-17T18:13:55.527+0000] {processor.py:183} INFO - Processing /mnt/c/Users/Shivam Gupta/OneDrive/Documents/Shivam_Developement/DATA_ENGINEERING/data_engineering_project/batch-etl-pyspark/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.160 seconds
